"""In-memory AS2 audit outbox skeleton (Alpha3g P0.6.35).

This module materializes the P0.6.31 audit persistence / transactional
outbox contract as an in-memory, production-facing skeleton. It deliberately
performs no file, network, database, CAS, queue, or relay I/O.

Boundary summary:
* ``AS2AuditEvent`` remains the deterministic payload and owns
  ``record_hash()``.
* ``OutboxAuditEnvelope`` is transport/persistence metadata and never
  participates in ``AS2AuditEvent.record_hash()``.
* ``InMemoryOutboxAuditSink`` implements ``AS2AuditSink`` and is explicit-DI
  only; ``NoOpAuditSink`` remains the default runtime sink.
* ``event_id`` is generated by the sink at append time and is deterministic for
  a given ``payload.record_hash()`` + ``sequence_number`` pair. Full cross-retry
  relay-idempotency requires a future logical event key and is intentionally
  not claimed by this skeleton.
"""
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from threading import RLock
from typing import Iterable

from synapse.canonical_service import stable_canonical_hash
from synapse.runtime.as2_audit_sink import AS2AuditEvent, AS2AuditSink

CHAIN_START = "CHAIN_START"
OUTBOX_ENVELOPE_SCHEMA_VERSION = "v1"

CRITICAL_AUDIT_EVENT_TYPES = frozenset(
    {
        "agent_quarantine",
        "gate_transition",
        "projection_completed",
        "projection_failed",
        "systemic_disable",
    }
)
DIAGNOSTIC_AUDIT_EVENT_TYPES = frozenset({"diagnostic", "observe", "telemetry"})


class AuditChainValidationResult(str, Enum):
    """Machine-readable audit hash-chain validation outcomes."""

    VALID_CHAIN_START = "valid_chain_start"
    VALID_LINK = "valid_link"
    MISSING_PREVIOUS = "missing_previous"
    BROKEN_PREVIOUS_HASH = "broken_previous_hash"


class OutboxAppendError(RuntimeError):
    """Base error raised by the in-memory audit outbox skeleton."""


class OutboxCapacityExceeded(OutboxAppendError):
    """Raised when a critical event cannot be accepted into a full outbox."""


class AuditChainViolation(OutboxAppendError):
    """Raised when an appended event would break the audit hash chain."""


@dataclass(frozen=True)
class OutboxAuditEnvelope:
    """Transport/persistence wrapper around a deterministic ``AS2AuditEvent``.

    Envelope fields are operational metadata for future persistence/relay
    layers. They are intentionally excluded from ``payload.record_hash()``.
    """

    event_id: str
    sequence_number: int
    payload: AS2AuditEvent
    wall_clock_timestamp: str | None = None
    partition_key: str | None = None
    relay_attempt_count: int = 0
    ingestion_node_id: str | None = None
    schema_version: str = OUTBOX_ENVELOPE_SCHEMA_VERSION


@dataclass(frozen=True)
class OutboxAppendResult:
    """Outcome of an outbox append attempt."""

    event_id: str
    sequence_number: int
    accepted: bool
    reason_code: str | None = None


def validate_chain_link(
    *,
    previous_envelope: OutboxAuditEnvelope | None,
    current_payload: AS2AuditEvent,
) -> AuditChainValidationResult:
    """Validate ``current_payload.previous_state_hash`` against the chain.

    ``CHAIN_START`` is the only valid first-record sentinel. ``None`` is treated
    as missing data, not as a valid chain start.
    """

    previous_hash = current_payload.previous_state_hash
    if previous_hash is None:
        return AuditChainValidationResult.MISSING_PREVIOUS
    if previous_envelope is None:
        if previous_hash == CHAIN_START:
            return AuditChainValidationResult.VALID_CHAIN_START
        return AuditChainValidationResult.BROKEN_PREVIOUS_HASH
    if previous_hash == previous_envelope.payload.record_hash():
        return AuditChainValidationResult.VALID_LINK
    return AuditChainValidationResult.BROKEN_PREVIOUS_HASH


class InMemoryOutboxAuditSink:
    """Append-only in-memory audit outbox skeleton.

    The sink is intended for explicit dependency injection in tests and future
    ENABLED_FOR_TEST harnesses. It is not a production persistence backend and
    performs no I/O.
    """

    def __init__(self, *, max_entries: int | None = None) -> None:
        if max_entries is not None and max_entries < 0:
            raise ValueError("max_entries must be non-negative or None")
        self._max_entries = max_entries
        self._outbox: list[OutboxAuditEnvelope] = []
        self._lock = RLock()

    def record(self, event: AS2AuditEvent) -> None:
        """Implement ``AS2AuditSink`` by appending ``event`` to the outbox."""

        self.append(event)

    def append(
        self,
        event: AS2AuditEvent,
        *,
        wall_clock_timestamp: str | None = None,
        partition_key: str | None = None,
        ingestion_node_id: str | None = None,
    ) -> OutboxAppendResult:
        """Append an audit event and return the generated envelope metadata.

        Critical events fail closed if the bounded queue is full. Diagnostic
        events are best-effort and may be dropped when the queue is full.
        Unknown event types are treated as critical by default.
        """

        with self._lock:
            sequence_number = len(self._outbox)
            event_id = self._event_id(event, sequence_number)
            if self._is_full():
                if self._is_diagnostic(event):
                    return OutboxAppendResult(
                        event_id=event_id,
                        sequence_number=sequence_number,
                        accepted=False,
                        reason_code="DROPPED_DIAGNOSTIC_OUTBOX_FULL",
                    )
                raise OutboxCapacityExceeded("critical AS2 audit event rejected because outbox is full")

            previous_envelope = self._outbox[-1] if self._outbox else None
            validation = validate_chain_link(previous_envelope=previous_envelope, current_payload=event)
            if validation not in (
                AuditChainValidationResult.VALID_CHAIN_START,
                AuditChainValidationResult.VALID_LINK,
            ):
                raise AuditChainViolation(f"audit chain validation failed: {validation.value}")

            envelope = OutboxAuditEnvelope(
                event_id=event_id,
                sequence_number=sequence_number,
                payload=event,
                wall_clock_timestamp=wall_clock_timestamp,
                partition_key=partition_key or event.correlation_id,
                ingestion_node_id=ingestion_node_id,
            )
            self._outbox.append(envelope)
            return OutboxAppendResult(event_id=event_id, sequence_number=sequence_number, accepted=True)

    @property
    def envelopes(self) -> tuple[OutboxAuditEnvelope, ...]:
        """Return an immutable snapshot of current outbox envelopes."""

        with self._lock:
            return tuple(self._outbox)

    def __len__(self) -> int:
        with self._lock:
            return len(self._outbox)

    def iter_payloads(self) -> Iterable[AS2AuditEvent]:
        """Return a snapshot iterator over deterministic payload events."""

        return (envelope.payload for envelope in self.envelopes)

    def _is_full(self) -> bool:
        return self._max_entries is not None and len(self._outbox) >= self._max_entries

    def _is_diagnostic(self, event: AS2AuditEvent) -> bool:
        if event.event_type in DIAGNOSTIC_AUDIT_EVENT_TYPES:
            return True
        if event.event_type in CRITICAL_AUDIT_EVENT_TYPES:
            return False
        return False

    def _event_id(self, event: AS2AuditEvent, sequence_number: int) -> str:
        return stable_canonical_hash(
            {
                "payload_hash": event.record_hash(),
                "sequence_number": sequence_number,
            }
        )


__all__ = [
    "AuditChainValidationResult",
    "AuditChainViolation",
    "CHAIN_START",
    "CRITICAL_AUDIT_EVENT_TYPES",
    "DIAGNOSTIC_AUDIT_EVENT_TYPES",
    "InMemoryOutboxAuditSink",
    "OUTBOX_ENVELOPE_SCHEMA_VERSION",
    "OutboxAppendError",
    "OutboxAppendResult",
    "OutboxAuditEnvelope",
    "OutboxCapacityExceeded",
    "validate_chain_link",
]


def _protocol_check(sink: AS2AuditSink) -> AS2AuditSink:
    """Return ``sink``; used only to keep the Protocol relationship explicit."""

    return sink
