"""Canonical controlled-change terminal outcomes, failure codes, and phase statuses."""

from __future__ import annotations

APPLIED = "APPLIED"
PATCH_REJECTED = "PATCH_REJECTED"
VERIFICATION_FAILED = "VERIFICATION_FAILED"
BASELINE_PREEXISTING_FAILURE = "BASELINE_PREEXISTING_FAILURE"
BASELINE_MUTATED_WORKTREE = "BASELINE_MUTATED_WORKTREE"
APPLICATION_STALE_BASE = "APPLICATION_STALE_BASE"
POLICY_REFUSED = "POLICY_REFUSED"
SAFETY_STATE_UNKNOWN = "SAFETY_STATE_UNKNOWN"
EVIDENCE_CONFLICT = "EVIDENCE_CONFLICT"
INTERNAL_ERROR = "INTERNAL_ERROR"

EXIT_CODES = {
    APPLIED: 0,
    PATCH_REJECTED: 11,
    VERIFICATION_FAILED: 12,
    BASELINE_PREEXISTING_FAILURE: 13,
    BASELINE_MUTATED_WORKTREE: 14,
    APPLICATION_STALE_BASE: 20,
    POLICY_REFUSED: 21,
    SAFETY_STATE_UNKNOWN: 22,
    EVIDENCE_CONFLICT: 23,
    INTERNAL_ERROR: 30,
}


def exit_code_for(outcome: str) -> int:
    return EXIT_CODES.get(outcome, EXIT_CODES[INTERNAL_ERROR])


UNSAFE_TARGET_REF_CURRENTLY_CHECKED_OUT = (
    "UNSAFE_TARGET_REF_CURRENTLY_CHECKED_OUT"
)
WORKTREE_DISCOVERY_FAILED = "WORKTREE_DISCOVERY_FAILED"
WORKTREE_DISCOVERY_AMBIGUOUS_BRANCH = (
    "WORKTREE_DISCOVERY_AMBIGUOUS_BRANCH"
)
EVIDENCE_REF_ALREADY_EXISTS = "EVIDENCE_REF_ALREADY_EXISTS"
EVIDENCE_REF_SYMBOLIC_CONFLICT = "EVIDENCE_REF_SYMBOLIC_CONFLICT"
EVIDENCE_REF_UPDATE_FAILED = "EVIDENCE_REF_UPDATE_FAILED"
EVIDENCE_REF_STATE_UNKNOWN = "EVIDENCE_REF_STATE_UNKNOWN"
NOT_ATTEMPTED = "NOT_ATTEMPTED"
COMPLETED_LEGACY_SEMANTICS = "COMPLETED_LEGACY_SEMANTICS"
EVIDENCE_CREATED = "EVIDENCE_CREATED"
